spring: 
  datasource:
    #driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: "{cipher}8f56ef6d8f583fac6ef2723537be7752b31045ae5983707ec154f55ea3a225a6"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
management:
  endpoints:
    web:  
      exposure:
        include: "*"