server:
  port: 8072
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance: 
    preferIpAddress: true  

spring:
  cloud:
    gateway:
      server: 
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: license-serivce
              predicates:
                - Path=/newlicsvc/**
              uri: lb://LICENSE-SERVICE
              filters:
                - RewritePath=/newlicsvc/(?<segment>.*), /v1/${segment}
            - id: organization-service
              predicates:
                - Path=/neworgsvc/**
              uri: lb://ORGANIZATION-SERVICE
              filters:
                - RewritePath=/neworgsvc/(?<segment>.*), /v1/${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:  
      access: unrestricted              